### GET request to example server
POST http://localhost:3001/producto/insertarProducto
Content-Type: application/json

{
  "tituloProducto": "Depilacion Intima XL",
  "descripcionProducto": "Servicio de depilación íntima, formato XS: cuidado delicado y acabado profesional.",
  "valorProducto": 14900,
  "categoriaProducto": 49,
  "subcategoria": 4,
  "imagenProducto": "https://picsum.photos/seed/depilacion1/800/600",
  "imagenProductoSegunda": "https://picsum.photos/seed/depilacion2/800/600",
  "imagenProductoTercera": "https://picsum.photos/seed/depilacion3/800/600",
  "imagenProductoCuarta": "https://picsum.photos/seed/depilacion4/800/600"
}






### POST request to example server
POST http://localhost:3001/producto/actualizarProducto
Content-Type: application/json

{
  "id_producto": 112,
  "tituloProducto": "Depilación Láser Axilas",
  "descripcionProducto": "Tratamiento de depilación láser profesional para axilas",
  "valorProducto": 29990,
  "categoriaProducto": 3,
  "subcategoria": 7,
  "imagenProducto": "https://tuservidor.cl/img/axilas-1.jpg",
  "imagenProductoSegunda": "https://tuservidor.cl/img/axilas-2.jpg",
  "imagenProductoTercera": "https://tuservidor.cl/img/axilas-3.jpg",
  "imagenProductoCuarta": "https://tuservidor.cl/img/axilas-4.jpg"
}





### POST request to example server
POST http://localhost:3001/producto/seleccionarPorSubcategoria
Content-Type: application/json

{
  "subCategoria": 24
}
